### ISSUE TITLE
Flexget install Raspberry PI !

### ISSUE THREAD

**Issue by kovbandi** [sdispater/pendulum#832] opened 2024-06-03 20:28 UTC
- [ x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [ x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Raspberry OS Bookworm 
- **Pendulum version**: 3.0.0

## Issue
Hello. I want to install pendulum 3.0.0 to install Flexget on a Raspberry Pi4 with the latest version of Raspbian. I always run into this error, I don't know what to do: 

`Building wheels for collected packages: pendulum
  Building wheel for pendulum (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pendulum (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Running `maturin pep517 build-wheel -i /usr/bin/python --compatibility off`
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.9 at /usr/bin/python
         Compiling target-lexicon v0.12.6
         Compiling python3-dll-a v0.2.9
         Compiling libc v0.2.139
         Compiling autocfg v1.1.0
         Compiling once_cell v1.17.1
         Compiling proc-macro2 v1.0.51
         Compiling unicode-ident v1.0.6
         Compiling quote v1.0.23
         Compiling syn v1.0.109
         Compiling lock_api v0.4.9
         Compiling pyo3-build-config v0.19.1
         Compiling parking_lot_core v0.9.7
         Compiling cc v1.0.79
         Compiling memoffset v0.9.0
         Compiling smallvec v1.10.0
         Compiling scopeguard v1.1.0
         Compiling cfg-if v1.0.0
         Compiling parking_lot v0.12.1
         Compiling libmimalloc-sys v0.1.35
         Compiling pyo3-ffi v0.19.1
         Compiling pyo3 v0.19.1
         Compiling unindent v0.1.11
         Compiling indoc v1.0.9
         Compiling mimalloc v0.1.39
         Compiling pyo3-macros-backend v0.19.1
         Compiling pyo3-macros v0.19.1
         Compiling _pendulum v3.0.0 (/home/pi/pendulum-3.0.0/rust)
      error: this arithmetic operation will overflow
        --> src/helpers.rs:59:20
         |
      59 |         seconds += ((146_097 - 10957) * SECS_PER_DAY as usize) as isize;
         |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to compute `135140_usize * 86400_usize`, which would overflow
         |
         = note: `#[deny(arithmetic_overflow)]` on by default

      error: could not compile `_pendulum` (lib) due to 1 previous error
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.9-64bit" PYO3_PYTHON="/usr/bin/python" PYTHON_SYS_EXECUTABLE="/usr/bin/python" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/pi/pendulum-3.0.0/rust/Cargo.toml" "--release" "--lib" "--crate-type" "cdylib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/usr/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pendulum
Failed to build pendulum
ERROR: Could not build wheels for pendulum, which is required to install pyproject.toml-based projects
`

**Comment by lucydog177** [comment] 2024-06-04 06:20
I'm getting the same error when compiling the latest Flexget because it depends on Pendulum-3.0.0.  I'm running a 32-bit OS, specifically:
```
Raspberry Pi OS (Legacy) Lite
  Release date: March 12th 2024
  System: 32-bit
  Kernel version: 6.1
  Debian version: 11 (bullseye)
```

**Comment by kovbandi** [comment] 2024-06-04 07:05
Hello. I tried to install an older version (Flexget 3.10.2) and it went up without any problems and works.

**Comment by Tomcat-Engineering** [comment] 2024-06-07 11:40
This issue (i.e. smaller `usize` on arm7 causing a potential overflow which the compiler rejects) is also causing the builds to fail on https://www.piwheels.org/project/pendulum/

**Comment by baptistefetet** [comment] 2024-09-04 19:46
I had the same problem with my debian bookworm 32 bits, and the solution proposed by kovbandi to install an old version worked for me
pip install flexget==3.10.2

**Comment by bdrung** [comment] 2024-09-05 14:12
The error message

```
error: this arithmetic operation will overflow
--> src/helpers.rs:59:20
|
59 | seconds += ((146_097 - 10957) * SECS_PER_DAY as usize) as isize;
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to compute 135140_usize * 86400_usize, which would overflow
|
= note: #[deny(arithmetic_overflow)] on by default
```

is bug https://github.com/sdispater/pendulum/issues/784 where I proposed a fix in https://github.com/sdispater/pendulum/pull/842

**Comment by Secrus** [comment] 2024-09-22 17:30
Closing as duplicate of #784

**Closed by Secrus** 2024-09-22 17:30 UTC
