### ISSUE TITLE
Can't install pendulum with pip install -t

### ISSUE THREAD

**Issue by alekna** [sdispater/pendulum#20] opened 2016-08-17 14:48 UTC
Pendulum package is missing when installed with `pip install -t`

```
~/tmp> pip install -t lib pendulum
Collecting pendulum
Collecting pytz (from pendulum)
  Using cached pytz-2016.6.1-py2.py3-none-any.whl
Collecting tzlocal (from pendulum)
Collecting python-dateutil (from pendulum)
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->pendulum)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: pytz, tzlocal, six, python-dateutil, pendulum
Successfully installed pendulum python-dateutil-2.5.3 pytz-2016.6.1 six-1.10.0 tzlocal-1.2.2

~/tmp> ls -l lib/
total 64
drwxrwxr-x 1 lauris lauris   276 Aug 17 17:41 dateutil
drwxrwxr-x 1 lauris lauris   154 Aug 17 17:41 python_dateutil-2.5.3.dist-info
drwxrwxr-x 1 lauris lauris   272 Aug 17 17:41 pytz
drwxrwxr-x 1 lauris lauris   154 Aug 17 17:41 pytz-2016.6.1.dist-info
drwxrwxr-x 1 lauris lauris   138 Aug 17 17:41 six-1.10.0.dist-info
-rw-rw-r-- 1 lauris lauris 30098 Aug 17 17:41 six.py
-rw-rw-r-- 1 lauris lauris 29545 Aug 17 17:41 six.pyc
drwxrwxr-x 1 lauris lauris   254 Aug 17 17:41 tzlocal
drwxrwxr-x 1 lauris lauris   154 Aug 17 17:41 tzlocal-1.2.2.dist-info

~/tmp> pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
```

**Comment by sdispater** [comment] 2016-08-17 15:01
That's strange, I can't seem to reproduce on OSX.

```
total 136
drwxr-xr-x  16 sebastien  staff    544 Aug 17 09:58 dateutil
drwxr-xr-x  22 sebastien  staff    748 Aug 17 09:58 pendulum
drwxr-xr-x   8 sebastien  staff    272 Aug 17 09:58 pendulum-0.5.dist-info
drwxr-xr-x   9 sebastien  staff    306 Aug 17 09:58 python_dateutil-2.5.3.dist-info
drwxr-xr-x  15 sebastien  staff    510 Aug 17 09:58 pytz
drwxr-xr-x   9 sebastien  staff    306 Aug 17 09:58 pytz-2016.6.1.dist-info
drwxr-xr-x   8 sebastien  staff    272 Aug 17 09:58 six-1.10.0.dist-info
-rw-r--r--   1 sebastien  staff  30098 Aug 17 09:58 six.py
-rw-r--r--   1 sebastien  staff  33653 Aug 17 09:58 six.pyc
drwxr-xr-x  15 sebastien  staff    510 Aug 17 09:58 tzlocal
drwxr-xr-x   9 sebastien  staff    306 Aug 17 09:58 tzlocal-1.2.2.dist-info
```

What OS do you have?

**Comment by alekna** [comment] 2016-08-17 15:20
I'm using Fedora 24. I'm able to reproduce it inside clean and isolated environment by using `Docker`

```
~> docker run -ti --rm fedora:24 /bin/bash
[root@9ac09ce6cc24 /]# dnf install -yq python-pip gcc redhat-rpm-config python-devel
[root@9ac09ce6cc24 /]# pip install -t /tmp/lib pendulum
Collecting pendulum
  Downloading pendulum-0.5.tar.gz (70kB)
    100% |################################| 73kB 5.9MB/s 
Collecting tzlocal (from pendulum)
  Downloading tzlocal-1.2.2.tar.gz
Collecting pytz (from pendulum)
  Downloading pytz-2016.6.1-py2.py3-none-any.whl (481kB)
    100% |################################| 483kB 145kB/s 
Collecting python-dateutil (from pendulum)
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
    100% |################################| 204kB 293kB/s 
Collecting six>=1.5 (from python-dateutil->pendulum)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: pytz, tzlocal, six, python-dateutil, pendulum
  Running setup.py install for tzlocal ... done
  Running setup.py install for pendulum ... done
Successfully installed pendulum python-dateutil pytz six tzlocal
You are using pip version 8.0.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

[root@9ac09ce6cc24 /]# ls -l /tmp/lib/
total 64
drwxr-xr-x 1 root root   276 Aug 17 15:17 dateutil
drwxr-xr-x 1 root root   154 Aug 17 15:17 python_dateutil-2.5.3.dist-info
drwxr-xr-x 1 root root   272 Aug 17 15:17 pytz
drwxr-xr-x 1 root root   154 Aug 17 15:17 pytz-2016.6.1.dist-info
drwxr-xr-x 1 root root   138 Aug 17 15:17 six-1.10.0.dist-info
-rw-r--r-- 1 root root 30098 Aug 17 15:17 six.py
-rw-r--r-- 1 root root 29545 Aug 17 15:17 six.pyc
drwxr-xr-x 1 root root   254 Aug 17 15:17 tzlocal
drwxr-xr-x 1 root root   182 Aug 17 15:17 tzlocal-1.2.2-py2.7.egg-info
[root@9ac09ce6cc24 /]# 
```

**Comment by sdispater** [comment] 2016-08-17 16:51
It might be linked to Fedora since I can't reproduce on a fresh install of Debian.

After checking further, it seems to be a problem with the C extensions build because if you do:

```
PENDULUM_EXTENSIONS=false pip install -t /tmp/lib pendulum -U
```

It installs correctly.

I don't exactly know right now what fails on fedora.

**Comment by alekna** [comment] 2016-08-17 16:59
Thanks. I'll fix it myself and submit PR.

**Comment by alekna** [comment] 2016-08-17 18:02
Solved.

**Comment by sdispater** [comment] 2016-08-17 18:15
I will repoen this issue for a bit because the underlying problem is not solved.

Your pull request deactivate the C extensions by default and you now have to explicitly set `PENDULUM_EXTENSIONS=1`. It is a good workaround for now but what I want is try to build the C extensions by default and fallback to the pure Python implementation if it fails.

For some reason on Fedora, there is a problem when building the extensions but it does not fail. The consequence is that `pendulum` is not properly installed.

**Comment by alekna** [comment] 2016-08-17 19:04
Ping me should you need any help testing it on Fedora.

**Comment by sdispater** [comment] 2016-08-17 19:53
It appears that the problem is caused by `pip`. See https://github.com/pypa/pip/issues/3056 and https://github.com/pypa/pip/pull/3694 for reference.

If I install `pip` from the `master` branch, everything is ok.

```
pip install git+https://github.com/pypa/pip.git@master#egg=pip -U
```

So we just have to wait for the next `pip` version to be released.

I will change back the `setup.py` file so that C extensions are built normally.

**Comment by alekna** [comment] 2016-08-17 20:07
What's wrong with the current implementation?

**Comment by sdispater** [comment] 2016-08-17 20:53
Basically, it prevented C extensions from being built if you did not explicitly set `PENDULUM_EXTENSIONS=1`. The expected behavior is to try to build extensions by default and fallback on pure python implementation if it fails.

**Comment by alekna** [comment] 2016-08-17 20:58
Please don't rollback. I will submit another patch.

**Comment by sdispater** [comment] 2016-08-17 20:59
I already rolled back (not much, just 2 lines modified)

**Comment by sdispater** [comment] 2016-08-19 14:49
I will close this for now since it's not a bug in Pendulum.

**Closed by sdispater** 2016-08-19 14:49 UTC
