### ISSUE TITLE
Remove deprecated datetime.datetime.utcfromtimestamp

### ISSUE THREAD

**Issue by 07pepa** [sdispater/pendulum#834] opened 2024-06-11 11:41 UTC
This is not a bug but should be addressed and is in source code so i will skip usual i have latest pendulum installed

## Issue
https://github.com/sdispater/pendulum/blob/3e3fec6a5b66759078c5ae39c736ca95b78adbef/src/pendulum/__init__.py#L295
_datetime.datetime.utcfromtimestamp has been deprecated since 3.12 see https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp

its replacement is datetime.fromtimestamp and did not see any changes since   python 3.6  this is supporting 3.8+ so migration should be easy https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp

**Comment by edgarrmondragon** [comment] 2024-06-12 20:12
This is clearly a duplicate of https://github.com/sdispater/pendulum/issues/830

**Closed** 2024-06-13 08:44 UTC
