### ISSUE TITLE
time for a release? 

### ISSUE THREAD

**Issue by kapilt** [sdispater/pendulum#744] opened 2023-09-06 19:28 UTC
per GitHub v2 last release was over 3 years ago. v3 alpha last release is almost a year old. anything community can do to help?

**Comment by radkujawa** [comment] 2023-09-07 15:47
I think [this](https://github.com/sdispater/pendulum/issues/600) is the ticket on new releases. I wrote 3 weeks ago a post there, but I got no reaction unfortunately :(

**Comment by Secrus** [comment] 2023-09-10 09:42
Closing as duplicate of #600

**Closed by Secrus** 2023-09-10 09:42 UTC
