### ISSUE TITLE
Pendulum==0.5.4 on ArchLinux timezone broken

### ISSUE THREAD

**Issue by Edke** [sdispater/pendulum#40] opened 2016-08-31 04:18 UTC
- python 3.5.2
- pendulum 0.5.2

```python
import pendulum
pendulum.now()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pendulum/pendulum.py", line 274, in now
    return cls.instance(dt, tz)
  File "/usr/lib/python3.5/site-packages/pendulum/pendulum.py", line 205, in instance
    tzinfo=tz
  File "/usr/lib/python3.5/site-packages/pendulum/pendulum.py", line 180, in __init__
    self._tz = self._safe_create_datetime_zone(tzinfo)
  File "/usr/lib/python3.5/site-packages/pendulum/pendulum.py", line 111, in _safe_create_datetime_zone
    return cls._local_timezone()
  File "/usr/lib/python3.5/site-packages/pendulum/pendulum.py", line 130, in _local_timezone
    return local_timezone()
  File "/usr/lib/python3.5/site-packages/pendulum/tz/__init__.py", line 25, in local_timezone
    return LocalTimezone.get()
  File "/usr/lib/python3.5/site-packages/pendulum/tz/local_timezone.py", line 25, in get
    name = cls.get_local_tz_name()
  File "/usr/lib/python3.5/site-packages/pendulum/tz/local_timezone.py", line 60, in get_local_tz_name
    return getattr(cls, 'get_tz_name_for_{}'.format(os))()
  File "/usr/lib/python3.5/site-packages/pendulum/tz/local_timezone.py", line 157, in get_tz_name_for_unix
    return Timezone.load(tzpath)
  File "/usr/lib/python3.5/site-packages/pendulum/tz/timezone.py", line 50, in load
    default_transition_type) = Loader.load(name)
  File "/usr/lib/python3.5/site-packages/pendulum/tz/loader.py", line 36, in load
    with pytz.open_resource(name) as f:
  File "/usr/lib/python3.5/site-packages/pytz-2016.6.1-py3.5.egg/pytz/__init__.py", line 96, in open_resource
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1208, in resource_stream
    self, resource_name
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1486, in get_resource_stream
    return io.BytesIO(self.get_resource_string(manager, resource_name))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1489, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1562, in _get
    return self.loader.get_data(path)
OSError: [Errno 0] Error: 'pytz/zoneinfo/usr/share/zoneinfo/Europe/Bratislava'
```
After reverting back to 0.5.2 it works as expected:

```python
import pendulum
pendulum.now()
<Pendulum [2016-08-31T06:17:32.144487+02:00]>
```

**Comment by sdispater** [comment] 2016-08-31 04:50
It might be linked to #34 and its associated pull request #35.

It stems from the use of the `open_resource()` function of pytz that seems to not check in the correct path.

Could you see if it works by using pytz directly?

```python
>>> import pytz

>>> pytz.timezone('Europe/Bratislava')

>>> pytz.open_resource('Europe/Bratislava')
```

**Comment by Edke** [comment] 2016-08-31 04:55
Sure.

```python
>>> import pytz
>>> pytz.timezone('Europe/Bratislava')
<DstTzInfo 'Europe/Bratislava' PMT+0:58:00 STD>
>>> pytz.open_resource('Europe/Bratislava')
<_io.BytesIO object at 0x7f08136f12b0>
```

**Comment by sdispater** [comment] 2016-08-31 04:57
Ok. So there is a problem when the `open_resource()` function is called from the `Loader` class of pendulum.

I will investigate further and get back to you.

**Comment by Edke** [comment] 2016-08-31 08:14
Great, no problem, we switched to 0.5.2 till resolved, thank you.

**Comment by sdispater** [comment] 2016-08-31 16:15
I am unable to reproduce on a fresh install of archlinux.

The difference I see is that `pytz` in your case is loaded from its `.egg` and probably does not have the `zoneinfo` directory in it. So it tries to default on the system `zoneinfo` directory but for some reason put `pytz/zoneinfo`.

How did you install your pytz package?

**Comment by sdispater** [comment] 2016-08-31 16:20
Its a problem that occurs only when using `easy_install` apparently. I will try to find a fix however I strongly suggest you use `pip` rather than `easy_install`.

**Comment by Edke** [comment] 2016-08-31 16:54
I have system wide package `python2-pytz`, therefore pytz python3 version was installed using sudo pip3.

**Comment by sdispater** [comment] 2016-08-31 19:27
I just pushed a fix on the `master` branch. Could you test if it fixes the issue for you?

`pip install git+https://github.com/sdispater/pendulum.git@master#egg=pendulum -U`

**Comment by Edke** [comment] 2016-09-01 07:22
Looks like it works:

```
kraken@thingol:~/sandbox                                                                                                 [09:20:55]
$ sudo pip3 install git+https://github.com/sdispater/pendulum.git@master#egg=pendulum -U
Collecting pendulum from git+https://github.com/sdispater/pendulum.git@master#egg=pendulum
  Cloning https://github.com/sdispater/pendulum.git (to master) to /tmp/pip-build-t0bw_4zh/pendulum
Requirement already up-to-date: tzlocal in /usr/lib/python3.5/site-packages/tzlocal-1.2.2-py3.5.egg (from pendulum)
Requirement already up-to-date: pytz in /usr/lib/python3.5/site-packages/pytz-2016.6.1-py3.5.egg (from pendulum)
Requirement already up-to-date: python-dateutil in /usr/lib/python3.5/site-packages/python_dateutil-2.5.3-py3.5.egg (from pendulum)
Requirement already up-to-date: six>=1.5 in /usr/lib/python3.5/site-packages (from python-dateutil->pendulum)
Installing collected packages: pendulum
  Found existing installation: pendulum 0.5.2
    Uninstalling pendulum-0.5.2:
      Successfully uninstalled pendulum-0.5.2
  Running setup.py install for pendulum ... done
Successfully installed pendulum-0.5.4
$ python3 
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
>>> pendulum.now()
<Pendulum [2016-09-01T09:21:41.109763+02:00]>
```

**Comment by sdispater** [comment] 2016-09-01 14:38
Ok. Thanks.

I will release the `0.5.5` version in a couple of hours.

**Comment by sdispater** [comment] 2016-09-01 15:49
Version `0.5.5` is out :-)

**Closed by sdispater** 2016-09-01 15:49 UTC
Labels: bug
