### ISSUE TITLE
Pendulum isn`t work properly, it show minus

### ISSUE THREAD

**Issue by herjh0405** [sdispater/pendulum#552] opened 2021-06-16 16:20 UTC
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: 
- **Pendulum version**: 

## Issue

![image](https://user-images.githubusercontent.com/54921730/122256516-1bebe880-cf0a-11eb-8daf-d8c6550c505b.png)

Why pendulum.parse('2021-01-26').week_of_month show that -49?

**Comment by emileten** [comment] 2021-12-19 08:29
I think we can close this as it was duplicated in https://github.com/sdispater/pendulum/issues/587 and the problem is getting solved there.

**Comment by Secrus** [comment] 2022-08-07 11:46
Closing as duplicate

**Closed by Secrus** 2022-08-07 11:46 UTC
Labels: duplicate
