### ISSUE TITLE
parse "2018-1-1" will get "2018-11-1"

### ISSUE THREAD

**Issue by zhangchunlin** [sdispater/pendulum#412] opened 2019-10-12 10:31 UTC
```
~/sandbox$ python
Python 3.6.5 (default, Nov 14 2018, 15:52:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pendulum import parse
>>> parse("2018-1-1")
DateTime(2018, 11, 1, 0, 0, 0, tzinfo=Timezone('UTC'))
>>> parse("2018-1-2")
DateTime(2018, 12, 1, 0, 0, 0, tzinfo=Timezone('UTC'))
>>> parse("2018-1-3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhangclb/.local/env3/lib/python3.6/site-packages/pendulum/parser.py", line 20, in parse
    return _parse(text, **options)
  File "/home/zhangclb/.local/env3/lib/python3.6/site-packages/pendulum/parser.py", line 36, in _parse
    parsed = base_parse(text, **options)
  File "/home/zhangclb/.local/env3/lib/python3.6/site-packages/pendulum/parsing/__init__.py", line 70, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/zhangclb/.local/env3/lib/python3.6/site-packages/pendulum/parsing/__init__.py", line 124, in _parse
    raise ParserError("Unable to parse string [{}]".format(text))
pendulum.parsing.exceptions.ParserError: Unable to parse string [2018-1-3]
>>> parse("2018-1-3",strict=False)
DateTime(2018, 1, 3, 0, 0, 0, tzinfo=Timezone('UTC'))
```

**Comment by maedox** [comment] 2019-11-01 09:28
You can work around it by being explicit: `pendulum.from_format('2018-1-1', 'YYYY-M-D')`

**Comment by zhangchunlin** [comment] 2019-11-03 01:48
@maedox  What's the format the result "2018-11-1" used?

**Comment by maedox** [comment] 2019-11-03 20:33
Not sure I understand the question... The format to parse 2018-11-1 is the same; `'YYYY-M-D'`
The M and D just drops the leading zero.

**Comment by zhangchunlin** [comment] 2019-11-04 01:54
I don't understand the logic to use the 'YYYY-M-D' with '2018-1-1' and get result "2018-11-1", I think it is wrong, or why not get "2018-11-11"? But "2018-11-11" is also rediculous.

**Comment by maedox** [comment] 2019-11-04 12:05
I think you misunderstood me. I agree there is an issue. I'm just saying
you can avoid it by using the code I suggested.

**Comment by zhangchunlin** [comment] 2019-11-06 05:39
Got it, thank you.

**Comment by GabrielSimonetto** [comment] 2020-09-19 13:29
Hi there!

I was taking a look at this issue, and it seems it is fixed on the newer versions:

```
# It seems to be using Y/M/D instead of Y/D/M as opposed to in the time of this issue
In [26]: parse("2018-1-2", strict=False)
Out[26]: DateTime(2018, 1, 2, 0, 0, 0, tzinfo=Timezone('UTC'))

In [27]: parse("2018-2-1", strict=False)
Out[27]: DateTime(2018, 2, 1, 0, 0, 0, tzinfo=Timezone('UTC'))

In [28]: parse("2018-2-1", strict=True)
ParserError: Unable to parse string [2018-2-1]
```

This seems like intended behaviour

Although, I would like to point out I couldn't find any tests targetted to this interaction, so I believe it was unintentionally fixed, could I make a PR testing this to make things official?

**Comment by GabrielSimonetto** [comment] 2020-09-19 14:11
Ok, my bad, this already is tested on `tests/parsing/test_parsing.py -- test_ymd_one_character`

This issue is ready to be closed

**Closed** 2022-08-07 11:33 UTC
